<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LH7U05CG636322G" name="com.atdd.demo.runners.RunDemoTest" tests="1" failures="0" timestamp="8 Oct 2018 14:20:25 GMT" time="220.560" errors="1">
  <testcase name="feature" time="220.560" classname="com.atdd.demo.runners.RunDemoTest">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The text is not entered.Screenshot captured">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The text is not entered.Screenshot captured
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.AssertionError: The text is not entered.Screenshot captured
	at org.testng.Assert.fail(Assert.java:94)
	at com.atdd.te.screenHelpers.FunctionalLibrary.enterText(FunctionalLibrary.java:944)
	at com.atdd.demo.te.stepdefinitons.ClaimStatusAndMessage.i_add_messages_to_Paid_claim(ClaimStatusAndMessage.java:127)
	at âœ½.When I add messages to Paid claim "8403","RCPDMP","TCL","20","1"(features/RxClaim/SWATHI/SN003292/SN003292_TC02.feature:36)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.atdd.demo.runners.RunDemoTest -->
